spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
  # JPA 설정
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
# 로그 레벨 설정
logging:
  level:
    # hibernate가 남기는 모든 로그가 debug 모드로 설정
    # JPA hibernate가 생성하는 SQL이 로거를 토앻서 찍히도록 하는 설정
    org.hibernate.SQL : debug
    org.hibernate.type: trace # 실제 파라미터값 찍어주는 설정
